services:
  medicalunitsystem:
    image: ${DOCKER_REGISTRY-}medicalunitsystem
    build:
      context: .
      dockerfile: MedicalUnitSystem/Dockerfile
    ports:
     - "5000:80"
    environment:
     - ConnectionStrings__DefaultConnection=Host=postgresdb;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  postgresdb:
     image: postgres:latest
     container_name: postgresdb
     restart: always
     ports:
         - "5432:5432"
     environment:
         POSTGRES_DB: ${POSTRES_DB}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
     volumes:
         - local_pgdata:/var/lib/postgressql/data
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
          - "8081:80"
      environment:
          PGADMIN_DEFAULT_EMAIL: david@gmail.com
          PGADMIN_DEFAULT_PASSWORD: test1234
      volumes:
          - pgadmin-data:/var/lib/pgadmin
volumes:
   local_pgdata:
   pgadmin-data: