apiVersion: v1
kind: Secret
metadata:
  name: gilead-secrets
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "Change_this_Strong_Password_123!"
  ConnectionStrings__GileadDb: "Server=gilead-sqlserver,1433;Database=GileadDb;User Id=sa;Password=Change_this_Strong_Password_123!;TrustServerCertificate=True"
  Redis__ConnectionString: "gilead-redis:6379"
