<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Gilead.Application\Gilead.Application.csproj" />
    <ProjectReference Include="..\Gilead.Domain\Gilead.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Gilead.DB\Tables\*.sql" Link="Gilead.DB\001_Tables\%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\Gilead.DB\TVPs\*.sql" Link="Gilead.DB\002_TVPs\%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\Gilead.DB\StoredProcedures\**\*.sql" Link="Gilead.DB\003_StoredProcedures\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="dbup-sqlserver" Version="7.2.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
